version: '3'
services:
  dochero_account_service:
    image: phongvanngo/dochero-account-service
    container_name: docHero_account_service
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=${ACCOUNT_SERVICE_DB_URI}
      - SPRING_DATASOURCE_PASSWORD=${ACCOUNT_SERVICE_DB_PASSWORD}
      - SPRING_DATASOURCE_USERNAME=${ACCOUNT_SERVICE_DB_USERNAME}
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=${SERVER_REGISTRY_URL}
    ports:
      - ${ACCOUNT_SERVICE_PORT}:8082