name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  version: ${{ github.sha }}
  dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
  dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
  server_host: ${{ secrets.SERVER_HOST }}
  server_username: ${{ secrets.SERVER_USERNAME }}
  server_password: ${{ secrets.SERVER_PASSWORD }}
  

jobs:

  check-variable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log variables
        run:
          echo $version;
          echo $dockerhub_username;
      

  login:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login To Dockerhub
      run:
        docker login --username=${dockerhub_username} --password=${dockerhub_password} 


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        echo $dockerhub_username;
        cd account-service;
        docker build . --file Dockerfile --tag phongvanngo/dochero-account-service:latest;
        docker tag phongvanngo/dochero-account-service:latest phongvanngo/dochero-account-service:$version;
        docker images;
        docker login --username=${dockerhub_username} --password=${dockerhub_password};
        docker push phongvanngo/dochero-account-service:$version;
        docker push phongvanngo/dochero-account-service:latest;
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 45.119.85.106
        username: novapo
        password: Novapo2503
        script: whoami
