name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  version: ${{ github.sha }}
  dockerhub_username: phongvanngo
  dockerhub_password: novapo2412
  server_host: ${{ secrets.SERVER_HOST }}
  server_username: ${{ secrets.SERVER_USERNAME }}
  server_password: ${{ secrets.SERVER_PASSWORD }}
  

jobs:

  check-variable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log variables
        run:
          echo $version;
      

  login:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: $dockerhub_username
          password: $dockerhub_password

  build:

    runs-on: ubuntu-latest

    steps:
    
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: $dockerhub_username
        password: $dockerhub_password
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        echo $dockerhub_username;
        cd account-service;
        docker build . --file Dockerfile --tag phongvanngo/dochero-account-service;
        docker tag phongvanngo/dochero-account-service:latest phongvanngo/dochero-account-service:$version;
        docker push phongvanngo/dochero-account-service:latest;
        docker images;
        docker push phongvanngo/dochero-account-service:$version;
        
  
      
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: $server_host
        username: $server_username
        password: $server_password
        script: whoami
